import React from "react";
import Head from "next/head";
import Layout from "../../components/Layout";
import styles from "../../styles/mdp.module.css";
import Banner from "../../components/Banner";
import SearchForm from "../../components/SearchForm";

export default function MotDePasse() {
  return (
    <Layout>
      <Head>
        <title>Modifier son mot de passe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.SearchForm}>
          <SearchForm />
          <Banner />
        </div>
        <div className={styles.compte}>
          <p>
            <span> &larr;</span>Retour au compte
          </p>
        </div>
        <h4 className={styles.title}>Modifier votre mot de passe </h4>

        <div className={styles.containerGlobal}>
          <div className={styles.forms}>
            <div className={styles.divlocation}>
              <label className={styles.label}>Mot de passe actuel</label>
              <input
                type="text"
                name="motdepasseactuel"
                id="motdepasseactuel"
                // className={styles.Input1}
              />
            </div>
            <div className={styles.divwatch1}>
              <label className={styles.label}>Nouveau mot de passe</label>
              <input
                type="text"
                name="nouveaumotdepasse"
                style={{ textIndent: 17 + "px" }}
                // className={styles.Input2}
              />
            </div>
            <div className={styles.divwatch2}>
              <label className={styles.label}>Confirmer mot de passe</label>
              <input
                type="text"
                name="departure"
                id="departure"
                // className={styles.Input3}
              />
            </div>
            <button className={styles.button}>Valider</button>
          </div>
        </div>
      </main>
    </Layout>
  );
}
