const data = {
  products: [
    {
      id: 1,
      name: "Poussette",
      category: "poussette",
      price: 20,
      isAvailable: true,
    },
    {
      id: 2,
      name: "Poussette",
      category: "poussette",
      price: 30,
      isAvailable: true,
    },
    {
      id: 3,
      name: "Poussette",
      category: "poussette",
      price: 10,
      isAvailable: true,
    },
    {
      id: 4,
      name: "Poussette",
      category: "poussette",
      price: 25,
      isAvailable: true,
    },
    {
      id: 5,
      name: "Lit à barreaux",
      category: "lit_barreaux",
      price: 12,
      isAvailable: false,
    },
    {
      id: 6,
      name: "Lit à barreaux",
      category: "lit_barreaux",
      price: 12,
      isAvailable: true,
    },
    {
      id: 7,
      name: "Poussette",
      category: "poussette",
      price: 20,
      isAvailable: true,
    },
    {
      id: 8,
      name: "Poussette",
      category: "poussette",
      price: 30,
      isAvailable: true,
    },
    {
      id: 9,
      name: "Poussette",
      category: "poussette",
      price: 10,
      isAvailable: true,
    },
    {
      id: 10,
      name: "Poussette",
      category: "poussette",
      price: 25,
      isAvailable: true,
    },
    {
      id: 11,
      name: "Lit à barreaux",
      category: "lit_barreaux",
      price: 12,
      isAvailable: false,
    },
    {
      id: 12,
      name: "Lit à barreaux",
      category: "lit_barreaux",
      price: 12,
      isAvailable: true,
    },
  ],
};
export default data;
