import React, { useState } from "react";
import Head from "next/head";
import Layout from "../../components/Layout";
import styles from "../../styles/mdp.module.css";

export default function ResetMdp() {
  const [email, setEmail] = useState("");
  const [showform, setShowForm] = useState(true);
  const [showResultMessage, setShowResultMessage] = useState(false);

  const handleSubmit = (e) => {
    e.preventDefault();
    setShowForm(!showform);
    setShowResultMessage(!showResultMessage);
  };
  return (
    <Layout>
      <Head>
        <title>Reset your Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        {showform && (
          <>
            <h4 className={styles.title1}>Réinitialisez votre mot de passe</h4>
            <div className={styles.containerGlobal}>
              <div className={styles.forms}>
                <form>
                  <label className={styles.label}>Entrez votre email</label>
                  <input
                    type="email"
                    name="email"
                    id="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    required
                  />
                  <button className={styles.button} onClick={handleSubmit}>
                    Envoyer
                  </button>
                </form>
              </div>
            </div>
          </>
        )}
        {showResultMessage && (
          <div className={styles.divMessage}>
            <h2 className={styles.title1}>Vérifier votre boite email</h2>
            <p className={styles.paragraphe1}>
              Si votre email existe dans notre base de données, vous allez
              recevoir un email vous expliquant les étapes à suivre pour
              réinitialiser votre mot de passe.
            </p>
            <div className={styles.email}>{email}</div>
            <div>
              <p className={styles.paragraphe1}>
                si vous ne voyez pas l'e-mail, vérifiez dans vos spams
              </p>
            </div>
            <button
              className={styles.button1}
              onClick={() => {
                setShowForm(!showform);
                setShowResultMessage(!showResultMessage);
              }}
            >
              Renvoyez-moi un nouveau lien
            </button>
          </div>
        )}
      </main>
    </Layout>
  );
}
