import React, { useState } from "react";
import Head from "next/head";
import toast, { Toaster } from "react-hot-toast";
import Layout from "../../components/Layout";
import styles from "../../styles/SendEmailMdp.module.css";
import axios from "axios";
//import { useRouter } from 'next/dist/client/router';

export default function ResetMdp() {
  // const router = useRouter();
  const [email, setEmail] = useState("");
  const [showform, setShowForm] = useState(true);
  const [showResultMessage, setShowResultMessage] = useState(false);
  const notify = () => toast.success("Email envoyé avec succès !");

  const handleSubmit = (e) => {
    e.preventDefault();
    axios
      .post("/api/users/reset-password-email", { email })
      .then(() => {
        setShowForm(!showform);
        setShowResultMessage(!showResultMessage);
      })
      .catch(() => {
        toast.error("email Not Found");
      });
    notify();
  };
  return (
    <Layout>
      <Head>
        <title>Reset your Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {showform && (
          <>
            <h4 className={styles.title}>Réinitialisez votre mot de passe</h4>
            <div className={styles.containerGlobal}>
              <div className={styles.forms}>
                <form onSubmit={handleSubmit}>
                  <label className={styles.label}>Entrez votre email : </label>
                  <input
                    type="email"
                    name="emailreset"
                    id="emailreset"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    required
                  />
                  <button type="submit" className={styles.button}>
                    Envoyer
                  </button>
                </form>
              </div>
            </div>
          </>
        )}
        {showResultMessage && (
          <div className={styles.divMessage}>
            <h2 className={styles.title1}>Vérifier votre boite email</h2>
            <span>
              <Toaster position="top-center" reverseOrder={true} />
            </span>
            <p className={styles.paragraphe1}>
              Si votre email existe dans notre base de données, vous allez
              recevoir un email vous expliquant les étapes à suivre pour
              réinitialiser votre mot de passe.
            </p>
            <div className={styles.email}>{email}</div>
            <p className={styles.paragraphe1}>
              si vous ne voyez pas l'e-mail, vérifiez dans vos spams
            </p>
            <button
              className={styles.button1}
              onClick={() => {
                setShowForm(!showform);
                setShowResultMessage(!showResultMessage);
              }}
            >
              Je veux un nouveau lien
            </button>
          </div>
        )}
      </main>
    </Layout>
  );
}
