/* eslint-disable prettier/prettier */
// eslint-disable-next-line prettier/prettier
import React from "react";
import Head from "next/head";
// eslint-disable-next-line prettier/prettier
import Layout from "../../components/Layout";

export default function Commandes() {
  return (
    <Layout>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Bienvenue sur notre blog</h1>
      </main>
    </Layout>
  );
}
