import Head from "next/head";
//*import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Page Index</title>
      </Head>
      <main>
        <h2>Here is the Home page</h2>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum
        perferendis voluptates exercitationem? Doloribus omnis cumque dolor
        eligendi blanditiis excepturi iusto! Inventore harum nam numquam. Autem,
        deserunt. Sint maiores aspernatur debitis. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. Officia facilis quia numquam dolorem neque
        voluptatem, aliquid repellendus iusto consequatur optio, libero, at
        incidunt ex perferendis sint delectus. Nemo, ipsam voluptate? Lorem
        ipsum dolor, sit amet consectetur adipisicing elit. Dolore accusamus
        quae adipisci nihil a quidem, eum voluptates ullam deleniti non
        temporibus neque soluta rem saepe hic. Alias, quo! Expedita, id! Lorem
        ipsum dolor sit amet consectetur adipisicing elit. Illum perferendis
        voluptates exercitationem? Doloribus omnis cumque dolor eligendi
        blanditiis excepturi iusto! Inventore harum nam numquam. Autem,
        deserunt. Sint maiores aspernatur debitis. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. Officia facilis quia numquam dolorem neque
        voluptatem, aliquid repellendus iusto consequatur optio, libero, at
        incidunt ex perferendis sint delectus. Nemo, ipsam voluptate? Lorem
        ipsum dolor, sit amet consectetur adipisicing elit. Dolore accusamus
        quae adipisci nihil a quidem, eum voluptates ullam deleniti non
        temporibus neque soluta rem saepe hic. Alias, quo! Expedita, id!
      </main>
    </div>
  );
}
